export const fontDetectionCandidates = [
  'Inter',
  'Roboto',
  'Arial',
  'Helvetica',
  'Segoe UI',
  'Calibri',
  'Times New Roman',
  'Georgia',
  'Garamond',
  'Palatino',
  'Montserrat',
  'Lato',
  'Open Sans',
  'Poppins',
  'Work Sans',
  'Merriweather',
  'Raleway',
  'Fira Sans',
  'Ubuntu',
  'Noto Sans',
  'Noto Serif',
  'Source Sans Pro',
  'Source Serif Pro',
  'Source Code Pro',
  'Fira Code',
  'Inconsolata',
  'JetBrains Mono',
  'Consolas',
  'Menlo',
  'Monaco',
  'Ubuntu Mono',
  'Tahoma',
  'Trebuchet MS',
  'Verdana',
  'Century Gothic',
  'Book Antiqua',
  'Palatino Linotype',
  'Cambria',
  'Candara',
  'Corbel',
  'Constantia',
  'Franklin Gothic Medium',
  'Arial Black',
  'Arial Narrow',
  'Brush Script MT',
  'Comic Sans MS',
  'Gabriola',
  'Ebrima',
  'Segoe Print',
  'Segoe Script',
  'Bahnschrift',
  'Courier New',
  'Cascadia Code',
  'Avenir',
  'Avenir Next',
  'Geneva',
  'Optima',
  'Lucida Grande',
  'Lucida Sans Unicode',
  'Gill Sans',
  'Futura',
  'American Typewriter',
  'Baskerville',
  'Big Caslon',
  'Bodoni 72',
  'Didot',
  'Copperplate',
  'Hoefler Text',
  'Chalkboard SE',
  'Marker Felt',
  'SFMono-Regular',
  'PingFang SC',
  'Hiragino Sans',
  'Skia',
  'Arial Italic',
  'Arial Bold',
  'Arial Bold Italic',
  'Calibri Light',
  'Calibri Light Italic',
  'Calibri Italic',
  'Calibri Bold',
  'Calibri Bold Italic',
  'Cambria Italic',
  'Cambria Bold',
  'Cambria Bold Italic',
  'Cambria Math',
  'Candara Light',
  'Candara Light Italic',
  'Candara Italic',
  'Candara Bold',
  'Candara Bold Italic',
  'Comic Sans MS Italic',
  'Comic Sans MS Bold',
  'Comic Sans MS Bold Italic',
  'Consolas Italic',
  'Consolas Bold',
  'Consolas Bold Italic',
  'Constantia Italic',
  'Constantia Bold',
  'Constantia Bold Italic',
  'Corbel Light',
  'Corbel Light Italic',
  'Corbel Italic',
  'Corbel Bold',
  'Corbel Bold Italic',
  'Courier New Italic',
  'Courier New Bold',
  'Courier New Bold Italic',
  'Ebrima Bold',
  'Franklin Gothic Medium Italic',
  'Gadugi',
  'Gadugi Bold',
  'Georgia Italic',
  'Georgia Bold',
  'Georgia Bold Italic',
  'HoloLens MDL2 Assets',
  'Impact',
  'Ink Free',
  'Javanese Text',
  'Leelawadee UI',
  'Leelawadee UI Semilight',
  'Leelawadee UI Bold',
  'Lucida Console',
  'Malgun Gothic',
  'Malgun Gothic Bold',
  'Malgun Gothic Semilight',
  'Marlett',
  'Microsoft Himalaya',
  'Microsoft JhengHei Light',
  'Microsoft JhengHei',
  'Microsoft JhengHei Bold',
  'Microsoft JhengHei UI Light',
  'Microsoft JhengHei UI',
  'Microsoft JhengHei UI Bold',
  'Microsoft New Tai Lue',
  'Microsoft New Tai Lue Bold',
  'Microsoft PhagsPa',
  'Microsoft PhagsPa Bold',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft Tai Le Bold',
  'Microsoft YaHei Light',
  'Microsoft YaHei',
  'Microsoft YaHei Bold',
  'Microsoft YaHei UI Light',
  'Microsoft YaHei UI',
  'Microsoft YaHei UI Bold',
  'Microsoft Yi Baiti',
  'MingLiU-ExtB',
  'PMingLiU-ExtB',
  'MingLiU_HKSCS-ExtB',
  'Mongolian Baiti',
  'MS Gothic',
  'MS PGothic',
  'MS UI Gothic',
  'MV Boli',
  'Myanmar Text',
  'Myanmar Text Bold',
  'Nirmala UI Semilight',
  'Nirmala UI',
  'Nirmala UI Bold',
  'Palatino Linotype Italic',
  'Palatino Linotype Bold',
  'Palatino Linotype Bold Italic',
  'Segoe MDL2 Assets',
  'Segoe Print Bold',
  'Segoe Script Bold',
  'Segoe UI Light',
  'Segoe UI Light Italic',
  'Segoe UI Semilight',
  'Segoe UI Semilight Italic',
  'Segoe UI Italic',
  'Segoe UI Semibold',
  'Segoe UI Semibold Italic',
  'Segoe UI Bold',
  'Segoe UI Bold Italic',
  'Segoe UI Black',
  'Segoe UI Black Italic',
  'Segoe UI Historic',
  'Segoe UI Emoji',
  'Segoe UI Symbol',
  'SimSun',
  'NSimSun',
  'SimSun-ExtB',
  'Sitka Small',
  'Sitka Small Italic',
  'Sitka Small Bold',
  'Sitka Small Bold Italic',
  'Sitka Text',
  'Sitka Text Italic',
  'Sitka Text Bold',
  'Sitka Text Bold Italic',
  'Sitka Subheading',
  'Sitka Subheading Italic',
  'Sitka Subheading Bold',
  'Sitka Subheading Bold Italic',
  'Sitka Heading',
  'Sitka Heading Italic',
  'Sitka Heading Bold',
  'Sitka Heading Bold Italic',
  'Sitka Display',
  'Sitka Display Italic',
  'Sitka Display Bold',
  'Sitka Display Bold Italic',
  'Sitka Banner',
  'Sitka Banner Italic',
  'Sitka Banner Bold',
  'Sitka Banner Bold Italic',
  'Sylfaen',
  'Symbol',
  'Tahoma Bold',
  'Times New Roman Italic',
  'Times New Roman Bold',
  'Times New Roman Bold Italic',
  'Trebuchet MS Italic',
  'Trebuchet MS Bold',
  'Trebuchet MS Bold Italic',
  'Verdana Italic',
  'Verdana Bold',
  'Verdana Bold Italic',
  'Webdings',
  'Wingdings',
  'Yu Gothic Light',
  'Yu Gothic Regular',
  'Yu Gothic Medium',
  'Yu Gothic Bold',
  'Yu Gothic UI Light',
  'Yu Gothic UI Semilight',
  'Yu Gothic UI Regular',
  'Yu Gothic UI Semibold',
  'Yu Gothic UI Bold',
  'Bitstream Charter',
  'C059',
  'Cantarell',
  'Cantarell Extra Bold',
  'Cantarell Light',
  'Cantarell Thin',
  'Courier 10 Pitch',
  'D050000L',
  'DejaVu Sans',
  'DejaVu Sans Mono',
  'DejaVu Serif',
  'DM Mono',
  'DM Mono Light',
  'DM Mono Medium',
  'Droid Sans Fallback',
  'FreeMono',
  'FreeSans',
  'FreeSerif',
  'Hack',
  'IBM Plex Mono',
  'IBM Plex Mono ExtLt',
  'IBM Plex Mono Light',
  'IBM Plex Mono Medm',
  'IBM Plex Mono SmBld',
  'IBM Plex Mono Text',
  'IBM Plex Mono Thin',
  'IBM Plex Sans',
  'IBM Plex Sans Arabic',
  'IBM Plex Sans Arabic ExtLt',
  'IBM Plex Sans Arabic Light',
  'IBM Plex Sans Arabic Medm',
  'IBM Plex Sans Arabic SmBld',
  'IBM Plex Sans Arabic Text',
  'IBM Plex Sans Arabic Thin',
  'IBM Plex Sans Condensed',
  'IBM Plex Sans Cond',
  'IBM Plex Sans Cond ExtLt',
  'IBM Plex Sans Cond Light',
  'IBM Plex Sans Cond Medm',
  'IBM Plex Sans Cond SmBld',
  'IBM Plex Sans Cond Text',
  'IBM Plex Sans Cond Thin',
  'IBM Plex Sans Devanagari',
  'IBM Plex Sans Devanagari ExtLt',
  'IBM Plex Sans Devanagari Light',
  'IBM Plex Sans Devanagari Medm',
  'IBM Plex Sans Devanagari SmBld',
  'IBM Plex Sans Devanagari Text',
  'IBM Plex Sans Devanagari Thin',
  'IBM Plex Sans Hebrew',
  'IBM Plex Sans Hebrew ExtLt',
  'IBM Plex Sans Hebrew Light',
  'IBM Plex Sans Hebrew Medm',
  'IBM Plex Sans Hebrew SmBld',
  'IBM Plex Sans Hebrew Text',
  'IBM Plex Sans Hebrew Thin',
  'IBM Plex Sans ExtLt',
  'IBM Plex Sans Light',
  'IBM Plex Sans Medm',
  'IBM Plex Sans SmBld',
  'IBM Plex Sans Text',
  'IBM Plex Sans Thin',
  'IBM Plex Sans Thai',
  'IBM Plex Sans Thai ExtLt',
  'IBM Plex Sans Thai Light',
  'IBM Plex Sans Thai Medm',
  'IBM Plex Sans Thai SmBld',
  'IBM Plex Sans Thai Text',
  'IBM Plex Sans Thai Thin',
  'IBM Plex Sans Thai Looped',
  'IBM Plex Sans Thai Looped ExtLt',
  'IBM Plex Sans Thai Looped Light',
  'IBM Plex Sans Thai Looped Medm',
  'IBM Plex Sans Thai Looped SmBld',
  'IBM Plex Sans Thai Looped Text',
  'IBM Plex Sans Thai Looped Thin',
  'IBM Plex Sans Var',
  'IBM Plex Serif',
  'IBM Plex Serif ExtLt',
  'IBM Plex Serif Light',
  'IBM Plex Serif Medm',
  'IBM Plex Serif SmBld',
  'IBM Plex Serif Text',
  'IBM Plex Serif Thin',
  'IPAGothic',
  'IPAゴシック',
  'IPAPGothic',
  'IPA Pゴシック',
  '䥐䅐䝯瑨楣',
  'Liberation Mono',
  'Liberation Sans',
  'Liberation Sans Narrow',
  'Liberation Serif',
  'Loma',
  'Nimbus Mono PS',
  'Nimbus Roman',
  'Nimbus Sans',
  'Nimbus Sans Narrow',
  'Noto Color Emoji',
  'Noto Kufi Arabic',
  'Noto Looped Lao',
  'Noto Looped Lao Bold',
  'Noto Looped Lao Regular',
  'Noto Looped Lao UI',
  'Noto Looped Lao UI Bold',
  'Noto Looped Lao UI Regular',
  'Noto Looped Thai',
  'Noto Looped Thai Bold',
  'Noto Looped Thai Regular',
  'Noto Looped Thai UI',
  'Noto Looped Thai UI Bold',
  'Noto Looped Thai UI Regular',
  'Noto Mono',
  'Noto Music',
  'Noto Naskh Arabic',
  'Noto Naskh Arabic UI',
  'Noto Nastaliq Urdu',
  'Noto Rashi Hebrew',
  'Noto Sans Adlam',
  'Noto Sans Adlam Unjoined',
  'Noto Sans Anatolian Hieroglyphs',
  'Noto Sans AnatoHiero',
  'Noto Sans Arabic',
  'Noto Sans Arabic UI',
  'Noto Sans Armenian',
  'Noto Sans Avestan',
  'Noto Sans Balinese',
  'Noto Sans Bamum',
  'Noto Sans Bassa Vah',
  'Noto Sans Batak',
  'Noto Sans Bengali',
  'Noto Sans Bengali UI',
  'Noto Sans Bhaiksuki',
  'Noto Sans Brahmi',
  'Noto Sans Buginese',
  'Noto Sans Buhid',
  'Noto Sans Canadian Aboriginal',
  'Noto Sans CanAborig',
  'Noto Sans Carian',
  'Noto Sans Caucasian Albanian',
  'Noto Sans CaucAlban',
  'Noto Sans Chakma',
  'Noto Sans Cham',
  'Noto Sans Cherokee',
  'Noto Sans CJK HK',
  'Noto Sans CJK JP',
  'Noto Sans CJK KR',
  'Noto Sans CJK SC',
  'Noto Sans CJK TC',
  'Noto Sans Coptic',
  'Noto Sans Cuneiform',
  'Noto Sans Cypriot',
  'Noto Sans Deseret',
  'Noto Sans Devanagari',
  'Noto Sans Devanagari UI',
  'Noto Sans Display',
  'Noto Sans Duployan',
  'Noto Sans Egyptian Hieroglyphs',
  'Noto Sans EgyptHiero',
  'Noto Sans Elbasan',
  'Noto Sans Elymaic',
  'Noto Sans Ethiopic',
  'Noto Sans Georgian',
  'Noto Sans Glagolitic',
  'Noto Sans Gothic',
  'Noto Sans Grantha',
  'Noto Sans Gujarati',
  'Noto Sans Gujarati UI',
  'Noto Sans Gunjala Gondi',
  'Noto Sans Gurmukhi',
  'Noto Sans Gurmukhi UI',
  'Noto Sans Hanifi Rohingya',
  'Noto Sans Hanunoo',
  'Noto Sans Hatran',
  'Noto Sans Hebrew',
  'Noto Sans Imperial Aramaic',
  'Noto Sans ImpAramaic',
  'Noto Sans Indic Siyaq Numbers',
  'Noto Sans Inscriptional Pahlavi',
  'Noto Sans InsPahlavi',
  'Noto Sans Inscriptional Parthian',
  'Noto Sans InsParthi',
  'Noto Sans Javanese',
  'Noto Sans Kaithi',
  'Noto Sans Kannada',
  'Noto Sans Kannada UI',
  'Noto Sans Kayah Li',
  'Noto Sans Kharoshthi',
  'Noto Sans Khmer',
  'Noto Sans Khmer UI',
  'Noto Sans Khojki',
  'Noto Sans Khudawadi',
  'Noto Sans Lao',
  'Noto Sans Lao UI',
  'Noto Sans Lepcha',
  'Noto Sans Limbu',
  'Noto Sans Linear A',
  'Noto Sans Linear B',
  'Noto Sans Lisu',
  'Noto Sans Lycian',
  'Noto Sans Lydian',
  'Noto Sans Mahajani',
  'Noto Sans Malayalam',
  'Noto Sans Malayalam UI',
  'Noto Sans Mandaic',
  'Noto Sans Manichaean',
  'Noto Sans Marchen',
  'Noto Sans Masaram Gondi',
  'Noto Sans Math',
  'Noto Sans Mayan Numerals',
  'Noto Sans Medefaidrin',
  'Noto Sans Meetei Mayek',
  'Noto Sans Mende Kikakui',
  'Noto Sans Meroitic',
  'Noto Sans Miao',
  'Noto Sans Modi',
  'Noto Sans Mongolian',
  'Noto Sans Mono',
  'Noto Sans Mono CJK HK',
  'Noto Sans Mono CJK JP',
  'Noto Sans Mono CJK KR',
  'Noto Sans Mono CJK SC',
  'Noto Sans Mono CJK TC',
  'Noto Sans Mro',
  'Noto Sans Multani',
  'Noto Sans Myanmar',
  'Noto Sans Myanmar UI',
  'Noto Sans Nabataean',
  'Noto Sans Newa',
  'Noto Sans New Tai Lue',
  'Noto Sans NKo',
  'Noto Sans Nushu',
  'Noto Sans Ogham',
  'Noto Sans Ol Chiki',
  'Noto Sans Old Hungarian',
  'Noto Sans OldHung',
  'Noto Sans Old Italic',
  'Noto Sans Old North Arabian',
  'Noto Sans OldNorArab',
  'Noto Sans Old Permic',
  'Noto Sans Old Persian',
  'Noto Sans Old Sogdian',
  'Noto Sans Old South Arabian',
  'Noto Sans OldSouArab',
  'Noto Sans Old Turkic',
  'Noto Sans Oriya',
  'Noto Sans Oriya UI',
  'Noto Sans Osage',
  'Noto Sans Osmanya',
  'Noto Sans Pahawh Hmong',
  'Noto Sans Palmyrene',
  'Noto Sans Pau Cin Hau',
  'Noto Sans PhagsPa',
  'Noto Sans Phoenician',
  'Noto Sans Psalter Pahlavi',
  'Noto Sans PsaPahlavi',
  'Noto Sans Rejang',
  'Noto Sans Runic',
  'Noto Sans Samaritan',
  'Noto Sans Saurashtra',
  'Noto Sans Sharada',
  'Noto Sans Shavian',
  'Noto Sans Siddham',
  'Noto Sans SignWriting',
  'Noto Sans SignWrit',
  'Noto Sans Sinhala',
  'Noto Sans Sinhala UI',
  'Noto Sans Sogdian',
  'Noto Sans Sora Sompeng',
  'Noto Sans Soyombo',
  'Noto Sans Sundanese',
  'Noto Sans Syloti Nagri',
  'Noto Sans Symbols',
  'Noto Sans Syriac',
  'Noto Sans Tagalog',
  'Noto Sans Tagbanwa',
  'Noto Sans Tai Le',
  'Noto Sans Tai Tham',
  'Noto Sans Tai Viet',
  'Noto Sans Takri',
  'Noto Sans Tamil',
  'Noto Sans Tamil Supplement',
  'Noto Sans Tamil UI',
  'Noto Sans Telugu',
  'Noto Sans Telugu UI',
  'Noto Sans Thaana',
  'Noto Sans Thai',
  'Noto Sans Thai UI',
  'Noto Sans Tifinagh',
  'Noto Sans Tifinagh Adrar',
  'Noto Sans Tifinagh Agraw Imazighen',
  'Noto Sans Tifinagh Ahaggar',
  'Noto Sans Tifinagh Air',
  'Noto Sans Tifinagh APT',
  'Noto Sans Tifinagh Azawagh',
  'Noto Sans Tifinagh Ghat',
  'Noto Sans Tifinagh Hawad',
  'Noto Sans Tifinagh Rhissa Ixa',
  'Noto Sans Tifinagh SIL',
  'Noto Sans Tifinagh Tawellemmet',
  'Noto Sans Tirhuta',
  'Noto Sans Ugaritic',
  'Noto Sans Vai',
  'Noto Sans Wancho',
  'Noto Sans Warang Citi',
  'Noto Sans Yi',
  'Noto Sans Zanabazar Square',
  'Noto Sans Zanabazar',
  'Noto Serif Ahom',
  'Noto Serif Armenian',
  'Noto Serif Balinese',
  'Noto Serif Bengali',
  'Noto Serif CJK HK',
  'Noto Serif CJK JP',
  'Noto Serif CJK KR',
  'Noto Serif CJK SC',
  'Noto Serif CJK TC',
  'Noto Serif Devanagari',
  'Noto Serif Display',
  'Noto Serif Dogra',
  'Noto Serif Ethiopic',
  'Noto Serif Georgian',
  'Noto Serif Grantha',
  'Noto Serif Gujarati',
  'Noto Serif Gurmukhi',
  'Noto Serif Hebrew',
  'Noto Serif Hmong Nyiakeng',
  'Noto Serif Kannada',
  'Noto Serif Khmer',
  'Noto Serif Khojki',
  'Noto Serif Lao',
  'Noto Serif Malayalam',
  'Noto Serif Myanmar',
  'Noto Serif Sinhala',
  'Noto Serif Tamil',
  'Noto Serif Tamil Slanted',
  'Noto Serif Tangut',
  'Noto Serif Telugu',
  'Noto Serif Thai',
  'Noto Serif Tibetan',
  'Noto Serif Yezidi',
  'Noto Traditional Nushu',
  'OpenSymbol',
  'P052',
  'Space Grotesk',
  'Space Grotesk Light',
  'Space Grotesk Medium',
  'Standard Symbols PS',
  'Symbola',
  'Noto Sans Symbols2',
  'Ubuntu Sans',
  'Ubuntu Sans Mono',
  'Unifont',
  'Unifont CSUR',
  'Unifont-JP',
  'Unifont Sample',
  'Unifont Upper',
  'URW Bookman',
  'URW Gothic',
  'WenQuanYi Zen Hei Mono',
  '文泉驛等寬正黑',
  '文泉驿等宽正黑',
  'WenQuanYi Zen Hei Sharp',
  '文泉驛點陣正黑',
  '文泉驿点阵正黑',
  'WenQuanYi Zen Hei',
  '文泉驛正黑',
  '文泉驿正黑',
  'Z003',
  'Arial',
  'Arial Italic',
  'Arial Bold',
  'Arial Bold Italic',
  'Arial Black',
  'Bahnschrift',
  'Calibri Light',
  'Calibri Light Italic',
  'Calibri',
  'Calibri Italic',
  'Calibri Bold',
  'Calibri Bold Italic',
  'Cambria',
  'Cambria Italic',
  'Cambria Bold',
  'Cambria Bold Italic',
  'Cambria Math',
  'Candara Light',
  'Candara Light Italic',
  'Candara',
  'Candara Italic',
  'Candara Bold',
  'Candara Bold Italic',
  'Cascadia Code ExtraLight *',
  'Cascadia Code ExtraLight Italic *',
  'Cascadia Code Light *',
  'Cascadia Code Light Italic *',
  'Cascadia Code SemiLight *',
  'Cascadia Code SemiLight Italic *',
  'Cascadia Code Regular *',
  'Cascadia Code Italic *',
  'Cascadia Code SemiBold *',
  'Cascadia Code SemiBold Italic *',
  'Cascadia Code Bold *',
  'Cascadia Code Bold Italic *',
  'Cascadia Mono ExtraLight *',
  'Cascadia Mono ExtraLight Italic *',
  'Cascadia Mono Light *',
  'Cascadia Mono Light Italic *',
  'Cascadia Mono SemiLight *',
  'Cascadia Mono SemiLight Italic *',
  'Cascadia Mono Regular *',
  'Cascadia Mono Italic *',
  'Cascadia Mono SemiBold *',
  'Cascadia Mono SemiBold Italic *',
  'Cascadia Mono Bold *',
  'Cascadia Mono Bold Italic *',
  'Comic Sans MS',
  'Comic Sans MS Italic',
  'Comic Sans MS Bold',
  'Comic Sans MS Bold Italic',
  'Consolas',
  'Consolas Italic',
  'Consolas Bold',
  'Consolas Bold Italic',
  'Constantia',
  'Constantia Italic',
  'Constantia Bold',
  'Constantia Bold Italic',
  'Corbel Light',
  'Corbel Light Italic',
  'Corbel',
  'Corbel Italic',
  'Corbel Bold',
  'Corbel Bold Italic',
  'Courier New',
  'Courier New Italic',
  'Courier New Bold',
  'Courier New Bold Italic',
  'Ebrima',
  'Ebrima Bold',
  'Franklin Gothic Medium',
  'Franklin Gothic Medium Italic',
  'Gabriola',
  'Gadugi',
  'Gadugi Bold',
  'Georgia',
  'Georgia Italic',
  'Georgia Bold',
  'Georgia Bold Italic',
  'HoloLens MDL2 Assets',
  'Impact',
  'Ink Free',
  'Javanese Text',
  'Leelawadee UI',
  'Leelawadee UI Semilight',
  'Leelawadee UI Bold',
  'Lucida Console',
  'Lucida Sans Unicode',
  'Malgun Gothic',
  'Malgun Gothic Bold',
  'Malgun Gothic Semilight',
  'Marlett',
  'Microsoft Himalaya',
  'Microsoft JhengHei Light',
  'Microsoft JhengHei',
  'Microsoft JhengHei Bold',
  'Microsoft JhengHei UI Light',
  'Microsoft JhengHei UI',
  'Microsoft JhengHei UI Bold',
  'Microsoft New Tai Lue',
  'Microsoft New Tai Lue Bold',
  'Microsoft PhagsPa',
  'Microsoft PhagsPa Bold',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft Tai Le Bold',
  'Microsoft YaHei Light',
  'Microsoft YaHei',
  'Microsoft YaHei Bold',
  'Microsoft YaHei UI Light',
  'Microsoft YaHei UI',
  'Microsoft YaHei UI Bold',
  'Microsoft Yi Baiti',
  'MingLiU-ExtB',
  'PMingLiU-ExtB',
  'MingLiU_HKSCS-ExtB',
  'Mongolian Baiti',
  'MS Gothic',
  'MS PGothic',
  'MS UI Gothic',
  'MV Boli',
  'Myanmar Text',
  'Myanmar Text Bold',
  'Nirmala UI Semilight',
  'Nirmala UI',
  'Nirmala UI Bold',
  'Palatino Linotype',
  'Palatino Linotype Italic',
  'Palatino Linotype Bold',
  'Palatino Linotype Bold Italic',
  'Segoe Fluent Icons *',
  'Segoe MDL2 Assets',
  'Segoe Print',
  'Segoe Print Bold',
  'Segoe Script',
  'Segoe Script Bold',
  'Segoe UI Light',
  'Segoe UI Light Italic',
  'Segoe UI Semilight',
  'Segoe UI Semilight Italic',
  'Segoe UI',
  'Segoe UI Italic',
  'Segoe UI Semibold',
  'Segoe UI Semibold Italic',
  'Segoe UI Bold',
  'Segoe UI Bold Italic',
  'Segoe UI Black',
  'Segoe UI Black Italic',
  'Segoe UI Emoji',
  'Segoe UI Historic',
  'Segoe UI Symbol',
  'Segoe UI Variable Display Light *',
  'Segoe UI Variable Display Semilight *',
  'Segoe UI Variable Display Regular *',
  'Segoe UI Variable Display Semibold *',
  'Segoe UI Variable Display Bold *',
  'Segoe UI Variable Small Light *',
  'Segoe UI Variable Small Semilight *',
  'Segoe UI Variable Small Regular *',
  'Segoe UI Variable Small Semibold *',
  'Segoe UI Variable Small Bold *',
  'Segoe UI Variable Text Light *',
  'Segoe UI Variable Text Semilight *',
  'Segoe UI Variable Text Regular *',
  'Segoe UI Variable Text Semibold *',
  'Segoe UI Variable Text Bold *',
  'SimSun',
  'NSimSun',
  'SimSun-ExtB',
  'Sitka Banner',
  'Sitka Banner Italic',
  'Sitka Banner Semibold *',
  'Sitka Banner Semibold Italic *',
  'Sitka Banner Bold',
  'Sitka Banner Bold Italic',
  'Sitka Display',
  'Sitka Display Italic',
  'Sitka Display Semibold *',
  'Sitka Display Semibold Italic *',
  'Sitka Display Bold',
  'Sitka Display Bold Italic',
  'Sitka Small',
  'Sitka Small Italic',
  'Sitka Small Semibold *',
  'Sitka Small Semibold Italic *',
  'Sitka Small Bold',
  'Sitka Small Bold Italic',
  'Sitka Heading',
  'Sitka Heading Italic',
  'Sitka Heading Semibold *',
  'Sitka Heading Semibold Italic *',
  'Sitka Heading Bold',
  'Sitka Heading Bold Italic',
  'Sitka Subheading',
  'Sitka Subheading Italic',
  'Sitka Subheading Semibold *',
  'Sitka Subheading Semibold Italic *',
  'Sitka Subheading Bold',
  'Sitka Subheading Bold Italic',
  'Sitka Text',
  'Sitka Text Italic',
  'Sitka Text Semibold *',
  'Sitka Text Semibold Italic *',
  'Sitka Text Bold',
  'Sitka Text Bold Italic',
  'Sylfaen',
  'Symbol',
  'Tahoma',
  'Tahoma Bold',
  'Times New Roman',
  'Times New Roman Italic',
  'Times New Roman Bold',
  'Times New Roman Bold Italic',
  'Trebuchet MS',
  'Trebuchet MS Italic',
  'Trebuchet MS Bold',
  'Trebuchet MS Bold Italic',
  'Verdana',
  'Verdana Italic',
  'Verdana Bold',
  'Verdana Bold Italic',
  'Webdings',
  'Wingdings',
  'Yu Gothic Light',
  'Yu Gothic Regular',
  'Yu Gothic Medium',
  'Yu Gothic Bold',
  'Yu Gothic UI Light',
  'Yu Gothic UI Semilight',
  'Yu Gothic UI Regular',
  'Yu Gothic UI Semibold',
  'Yu Gothic UI Bold',
];


